Capstone-Projects-2025-Spring/aac-go-fish

- README.md
> added feature requirements to the readme.

- documentation/docs/requirements/system-overview.md
Added content to system overview page
> system overview updated

- documentation/docs/requirements/_category_.json
Just a short description, similar to [the reference](https://capstone-projects-2023-spring.github.io/project-virtual-pet/docs/category/requirements-specification).
> Update Requirements Specification section wording

- documentation/docs/requirements/features-and-requirements.md
- documentation/docs/requirements/general-requirements.md
- More professional language and discreet categories for Features and Requirements based the sample documents
- General requirements are more general
- Added go fish rules (Ian told me to lol)
> Rewritten feature and requirement sections

- documentation/docs/requirements/use-case-descriptions.md
I changed the use cases based on the feedback we got, and added hyperlinks to starting use cases.
I am wondering if we need use cases for like "non actions" as in its not your turn or action, but you are the one getting cards taken from or someone else uses AAC?
> Change use cases based on feedback on documentation

- documentation/docs/requirements/features-and-requirements.md
Based on feedback from Friday before we send our docs to stakeholders
> Revised Features and Requirements page

- documentation/docs/system-architecture/development-environment.md
I need someone to add more tools to the frontend section.
> Add development environment docs

- backend/hello.py
I made a mistake when I was resolving a merge from the last PR. This should fix it
> Fix bad resolve from previous PR

- backend/hello.py
Added code for creating a lobby and getting lobby info
> Lobby creation and get lobby details

- documentation/docs/system-architecture/component-overview.md
Short description of the demo page's functionality
> Added react page info

- documentation/docs/requirements/use-case-descriptions.md
I created sequence diagrams for all use cases using mermaid js, and a new use case where a user is receiving AAC game communication from other users.
Since the directions described that they must show data flow, I included backend interactions and other user's interacting with the backend through their own web applications.
> All use case sequence diagrams and new use case for receiving AAC comms

- documentation/docs/requirements/use-case-descriptions.md
- documentation/docs/system-architecture/use-case-sequences.md
Moved the sequence diagrams to the system architecture portion of the documentation
> AGTC-53 AGTC-45 Moved sequence diagrams to system architecture section

- documentation/docs/requirements/use-case-descriptions.md
- documentation/docs/system-architecture/use-case-sequences.md
We agreed on having an infinite deck or a deck that refreshes.
This means users will not completely run out of cards and this will reduce isolation.
Use case descriptions and diagrams for these cases have been removed to reflect that.
> [AGTC-82] Removed use case descriptions/diagrams for running out completely

- compose.yaml
- frontend/Dockerfile
Added a Dockerfile in the frontend folder to run React dev server in a container, updated the docker-compose file to include the frontend
> dockerized for local development

- documentation/docs/requirements/features-and-requirements.md
Took the features and requirements we wrote in docs together and converted it to markdown.
Aligned functional requirements with game rules.
Put game rules in functional requirements based on Thanh's feedback on our requirements documentation assignment.
> [AGTC-85] Formatted google doc features and requirements to markdown

- .github/workflows/contribute.yml
- .github/workflows/spelling.yml
- backend/dependencies.py
- backend/hello.py
- backend/models.py
- backend/tests/test_example.py
- backend/tests/test_models.py
Added return types and docstrings to functions, removed some unused code, and fixed styling issues
> [AGTC-73] Update current code to follow pre-commit rules

- documentation/docs/requirements/features-and-requirements.md
- documentation/docs/requirements/system-overview.md
Changed priority of features.
Elaborated on manager/employee interaction.
Talked about challenging previous social dynamics in project abstract.
> Changed project abstract and features and requirements based on feedback

- documentation/docs/requirements/use-case-descriptions.md
new use cases for the new game
> AGTC-101 updated docs for use cases for cooking game

- documentation/static/htmlcov/class_index.html
- documentation/static/htmlcov/function_index.html
- documentation/static/htmlcov/index.html
- frontend/src/App.css
- frontend/src/App.js
- frontend/src/components/AACBoard.css
- frontend/src/components/AACBoard.js
- frontend/src/components/ManagerActions.css
- frontend/src/components/ManagerActions.js
- Manager can see what’s picked.
- created a text-based interface that logs when items are sent, orders are received, and items are given to the customer.
- “Send Items” plays each item’s audio and then clears them
> [AGTC-116] text based UI on frontend displaying game actions manager

- frontend/src/App.js
- frontend/src/components/CustomerOrder.js
Unsure if this is necessary or not, but figured I would see what it looked like with no get order button and share to see if everyone finds it useful
> Remove get order button, receive order button now has its functionality

- backend/hello.py
- backend/logging/development.toml
- backend/logging/production.toml
- backend/logging_config.py
- pyproject.toml
- uv.lock
Mostly stolen from another project I worked on. Configured for pretty logs in dev and json in prod.
> [AGTC-171] Add logging for web app

- backend/game.py
- backend/tests/test_game.py
- backend/tests/test_ws.py
- documentation/docs/requirements/features-and-requirements.md
https://temple-cis-projects-in-cs.atlassian.net/browse/AGTC-142
> [AGTC-142] Web application should grade orders based on correctness

- backend/dependencies.py
- backend/game.py
- backend/game_state.py
- backend/hello.py
- backend/models.py
- backend/tests/test_models.py
We should really think about how we want the `PlayerLeave` message to behave, that is, do we want the frontend to send it before shutting down if possible, or should we have the backend detect it by the websocket closing? Maybe a combination of both?
> [AGTC-185] Web application should broadcast lobby lifecycle events

- backend/game.py
Forgot to add this before, oopsies.
> Send role assignment to clients

- frontend/src/App.jsx
> Add missing break

- frontend/src/components/HomePage.css
- frontend/src/components/HomePage.jsx
- frontend/src/components/Lobby/Lobby.css
- frontend/src/components/Lobby/Lobby.jsx
Adds a new "Play All" button to the lobby screen once create lobby is pressed. The button splits the lobby code and plays the items in order
> Agtc 206 add aac button on homepage to read the lobby code

- backend/dependencies.py
- backend/game.py
- backend/game_state.py
- backend/hello.py
Considered adding a regression test to `backend/tests/test_ws.py`, but unsure how to test it.
> [AGTC-191] Responds to start game message even if already started

- compose.dev.yaml
- compose.yaml
- frontend/Dockerfile
- frontend/src/WebSocketContext.jsx
- frontend/src/components/HomePage.jsx
- nginx.conf
- nginx.dev.conf
HTTPS now works on 
[https://bankruptcyassociation.com/](https://bankruptcyassociation.com/)
The prod image rn is outdated though so the frontend is not making requests to https backend rn but should be fine once new image is made.
> Add using ssl certificate and https routes

- documentation/static/openapi.yaml
- frontend/src/components/Burger/BurgerBuilder.css
- frontend/src/components/HomePage.css
- frontend/src/components/HomePage.jsx
- frontend/src/components/Score/Score.jsx
This PR covers 2 tickets related to catching frontend up to backend changes:
- [AGTC-228 Frontend handles new score correctly](https://temple-cis-projects-in-cs.atlassian.net/browse/AGTC-228) following backend score changing to an int for cents to avoid float issues
- [Frontend gives a lobby full error message when attempting to join a full lobby](https://temple-cis-projects-in-cs.atlassian.net/browse/AGTC-230) following new API errors for cases other than 'Lobby Not Found'
- Updated documentation for the new API errors
> Score Formatting & Lobby Error Handling

- frontend/public/index.html
- frontend/src/components/HomePage.jsx
- frontend/src/components/Modal/ErrorModal.jsx
- frontend/src/components/Modal/Modal.css
- fixed css error for game complete screen
- added error modal to display lobby errors
> ATGC-244 popup modal to present lobby joining errors

- frontend/src/components/AACBoard/SelectedItemsDisplay.jsx
You can now remove ingredients like you used to be able to
> Re-add X button

- compose.yaml
Added `GF_AUTH_DISABLE_LOGIN_FORM: true`
> Disable basic auth form
